import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { runAgentCommand } from "./agent-runner.js";
import { buildConsolidatorPrompt } from "./playtest-prompts.js";
import { SEVERITY_WEIGHT, SEVERITIES } from "./playtest-feedback.js";

type Severity = (typeof SEVERITIES)[number];

const DEFAULT_SESSIONS_FILE = "playtest-feedback/sessions.jsonl";
const DEFAULT_DIGEST_FILE = "PLAYTEST_DIGEST.md";
const DEFAULT_WATERMARK_FILE = "playtest-feedback/.watermark";
const HEADER =
  "# Playtest Digest\n\nAuto-generated by `npm run playtest:consolidate`. Newest window on top. The coding agent reads the top section at the start of each planning window.\n";

// Ideal "true ending" scenes (kept in sync with src/score.ts).
const IDEAL_ENDINGS = new Set([
  "true_ending",
  "mara_handoff_true_ending",
  "passenger_true_ending",
  "passenger_answered_true_ending",
  "passenger_counted_true_ending",
  "passenger_manifest_handoff_true_ending",
  "passenger_answered_handoff_true_ending",
  "passenger_helped_true_ending",
  "passenger_conductor_true_ending",
  "passenger_keepsake_true_ending",
  "passenger_newspaper_true_ending",
  "passenger_mitten_true_ending"
]);

const CONFIDENCE_WEIGHT: Record<string, number> = { high: 1.5, med: 1, low: 0.6 };
const SEVERITY_ORDER: Record<Severity, number> = { S0: 0, S1: 1, S2: 2, S3: 3, S4: 4 };

interface CompactIssue {
  id: string;
  sev: Severity;
  category: string;
  scene?: string;
  confidence?: string;
  ev?: string;
}

interface CompactRecord {
  run_id: string;
  ts: string;
  model: string;
  persona: string;
  variant: string;
  ended: boolean;
  final_scene: string;
  score: number;
  max_score: number;
  turns: number;
  stuck_at: string | null;
  parse_error?: boolean;
  kept?: string;
  issues: CompactIssue[];
}

interface Cluster {
  id: string;
  category: string;
  sev: Severity;
  freq: number;
  personas: Set<string>;
  models: Set<string>;
  scenes: Set<string>;
  confidence: string;
  evidence: string;
  priority: number;
}

export interface ConsolidateOptions {
  sessionsFile?: string;
  digestFile?: string;
  watermarkFile?: string;
  all?: boolean;
  now?: Date;
  consolidateCmd?: string;
  timeoutMs?: number;
  write?: boolean;
}

export interface ConsolidateResult {
  windowStart: string;
  windowEnd: string;
  records: number;
  section: string | null;
  clusters: Cluster[];
}

function median(values: number[]): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid];
}

function tally(values: string[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const v of values) out[v] = (out[v] ?? 0) + 1;
  return out;
}

function topEntries(counts: Record<string, number>, n: number): string {
  return (
    Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, n)
      .map(([k, v]) => `${k}:${v}`)
      .join(", ") || "none"
  );
}

function buildClusters(records: CompactRecord[]): Cluster[] {
  const map = new Map<string, Cluster>();
  for (const record of records) {
    for (const issue of record.issues) {
      let cluster = map.get(issue.id);
      if (!cluster) {
        cluster = {
          id: issue.id,
          category: issue.category,
          sev: issue.sev,
          freq: 0,
          personas: new Set(),
          models: new Set(),
          scenes: new Set(),
          confidence: issue.confidence ?? "med",
          evidence: issue.ev ?? "",
          priority: 0
        };
        map.set(issue.id, cluster);
      }
      cluster.freq += 1;
      cluster.personas.add(record.persona);
      cluster.models.add(record.model);
      if (issue.scene) cluster.scenes.add(issue.scene);
      if (SEVERITY_ORDER[issue.sev] < SEVERITY_ORDER[cluster.sev]) cluster.sev = issue.sev;
      if (
        (CONFIDENCE_WEIGHT[issue.confidence ?? "med"] ?? 1) >
        (CONFIDENCE_WEIGHT[cluster.confidence] ?? 1)
      ) {
        cluster.confidence = issue.confidence ?? "med";
      }
      if (!cluster.evidence && issue.ev) cluster.evidence = issue.ev;
    }
  }

  for (const cluster of map.values()) {
    cluster.priority =
      SEVERITY_WEIGHT[cluster.sev] *
      cluster.freq *
      cluster.personas.size *
      (CONFIDENCE_WEIGHT[cluster.confidence] ?? 1);
  }

  return [...map.values()].sort((a, b) => b.priority - a.priority);
}

function isPromoted(cluster: Cluster): boolean {
  if (cluster.sev === "S0" || cluster.sev === "S1") return true;
  if (cluster.sev === "S2" && cluster.freq >= 2) return true;
  if (cluster.sev === "S3" && cluster.freq >= 4) return true;
  return cluster.personas.size >= 2;
}

const ACTION_BY_CATEGORY: Record<string, string> = {
  fairness: "foreshadow or soften the failure",
  navigation: "add signposting / clearer next step",
  signposting: "make the next objective discoverable",
  goal: "clarify the player's objective earlier",
  choice_label: "disambiguate choice labels",
  pacing: "tighten pacing / trim filler",
  bug: "fix the defect",
  engine: "fix the engine/state issue",
  text: "fix the text",
  continuity: "fix the continuity break",
  story: "strengthen the narrative beat",
  agency: "give the choice real consequence",
  reward: "acknowledge the action / reward",
  ux: "improve the interaction",
  other: "investigate"
};

function previousIds(digestText: string): Set<string> {
  const match = digestText.match(/<!-- ids: ([^>]*) -->/);
  if (!match) return new Set();
  return new Set(
    match[1]
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
  );
}

export async function consolidate(options: ConsolidateOptions = {}): Promise<ConsolidateResult> {
  const sessionsFile = options.sessionsFile ?? DEFAULT_SESSIONS_FILE;
  const digestFile = options.digestFile ?? DEFAULT_DIGEST_FILE;
  const watermarkFile = options.watermarkFile ?? DEFAULT_WATERMARK_FILE;
  const now = options.now ?? new Date();
  const write = options.write ?? true;

  let raw = "";
  try {
    raw = await readFile(sessionsFile, "utf8");
  } catch {
    return {
      windowStart: "",
      windowEnd: now.toISOString(),
      records: 0,
      section: null,
      clusters: []
    };
  }

  let watermark = "";
  if (!options.all) {
    try {
      watermark = (await readFile(watermarkFile, "utf8")).trim();
    } catch {
      watermark = "";
    }
  }

  const records: CompactRecord[] = [];
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const record = JSON.parse(trimmed) as CompactRecord;
      if (watermark && record.ts <= watermark) continue;
      records.push(record);
    } catch {
      // skip malformed line
    }
  }

  const windowStart = watermark || (records[0]?.ts ?? now.toISOString());
  const windowEnd = now.toISOString();

  if (records.length === 0) {
    return { windowStart, windowEnd, records: 0, section: null, clusters: [] };
  }

  const clusters = buildClusters(records);
  const promoted = clusters.filter(isPromoted);
  const noise = clusters.filter((c) => !isPromoted(c));

  // Quant
  const endedCount = records.filter((r) => r.ended).length;
  const idealCount = records.filter((r) => IDEAL_ENDINGS.has(r.final_scene)).length;
  const scores = records.map((r) => r.score);
  const turns = records.map((r) => r.turns);
  const endingDist = tally(records.map((r) => r.final_scene));
  const stuckDist = tally(records.filter((r) => r.stuck_at).map((r) => r.stuck_at as string));
  const personaDist = tally(records.map((r) => r.persona));
  const modelDist = tally(records.map((r) => r.model));
  const parseErrors = records.filter((r) => r.parse_error).length;

  // Optional LLM judge for theme naming + priorities (data-grounded only).
  const consolidateCmd = options.consolidateCmd ?? process.env.AI_PLAYTEST_CONSOLIDATE_CMD;
  let judgePriorities: Array<{ id: string; action: string; scenes?: string[]; add_test?: string }> =
    [];
  if (consolidateCmd && promoted.length > 0) {
    const aggregate = JSON.stringify(
      promoted.slice(0, 15).map((c) => ({
        id: c.id,
        category: c.category,
        sev: c.sev,
        freq: c.freq,
        personas: c.personas.size,
        scenes: [...c.scenes],
        evidence: c.evidence
      }))
    );
    const result = await runAgentCommand(
      consolidateCmd,
      buildConsolidatorPrompt({ windowStart, windowEnd, aggregateJson: aggregate }),
      { timeoutMs: options.timeoutMs ?? Number(process.env.AI_PLAYTEST_TIMEOUT_MS ?? 120000) }
    );
    const match = result.output.match(/\{[\s\S]*\}/);
    if (match) {
      try {
        const parsed = JSON.parse(match[0]);
        if (Array.isArray(parsed.priorities)) judgePriorities = parsed.priorities;
      } catch {
        // fall back to data-derived priorities
      }
    }
  }

  // Data-derived priorities fallback (never fabricated).
  const priorities =
    judgePriorities.length > 0
      ? judgePriorities
      : promoted.slice(0, 5).map((c) => ({
          id: c.id,
          action: ACTION_BY_CATEGORY[c.category] ?? "investigate",
          scenes: [...c.scenes],
          add_test: `repro for ${c.id}`
        }));

  // Persisting / resolved vs previous digest
  let digestText = "";
  try {
    digestText = await readFile(digestFile, "utf8");
  } catch {
    digestText = "";
  }
  const prevIds = previousIds(digestText);
  const currentIds = promoted.map((c) => c.id);
  const persisting = currentIds.filter((id) => prevIds.has(id));
  const resolved = [...prevIds].filter((id) => !currentIds.includes(id));

  const date = windowEnd.slice(0, 10);
  const lines: string[] = [];
  lines.push(`## ${date} (window ${windowStart} -> ${windowEnd})`);
  lines.push(`<!-- ids: ${currentIds.join(", ")} -->`);
  lines.push(
    `meta: sessions=${records.length} models=[${topEntries(modelDist, 6)}] ` +
      `personas=[${topEntries(personaDist, 7)}] parse_errors=${parseErrors}`
  );
  lines.push(
    `quant: ended=${Math.round((endedCount / records.length) * 100)}% ` +
      `true_ending=${Math.round((idealCount / records.length) * 100)}% ` +
      `median_turns=${median(turns)} score_avg=${(scores.reduce((a, b) => a + b, 0) / records.length).toFixed(1)} ` +
      `best=${Math.max(...scores)} endings=[${topEntries(endingDist, 6)}] stuck_top=[${topEntries(stuckDist, 5)}]`
  );
  lines.push("");
  lines.push("### Ranked issues (freq x sev)");
  if (promoted.length === 0) {
    lines.push("- none promoted this window");
  } else {
    promoted.slice(0, 15).forEach((c, i) => {
      const crossModel = c.models.size >= 2 ? " [cross-model]" : "";
      const scene = [...c.scenes][0] ?? "?";
      lines.push(
        `${i + 1}. [${c.sev} ${c.category}][${c.freq}/${records.length}][p${c.personas.size}]${crossModel} ` +
          `${c.id} @${scene} — ${c.evidence || "(no snippet)"} (prio ${Math.round(c.priority)})`
      );
    });
  }
  lines.push("");
  lines.push("### Do not overreact (one-off / low-confidence)");
  lines.push(
    noise.length === 0
      ? "- none"
      : noise
          .slice(0, 10)
          .map((c) => `- ${c.id} [${c.sev} ${c.category}] freq=${c.freq} p=${c.personas.size}`)
          .join("\n")
  );
  lines.push("");
  const working = [...new Set(records.map((r) => r.kept).filter(Boolean))].slice(0, 6);
  lines.push("### Working (preserve)");
  lines.push(working.length === 0 ? "- none reported" : working.map((w) => `- ${w}`).join("\n"));
  lines.push("");
  lines.push(`### Persisting / resolved`);
  lines.push(
    `persisting: ${persisting.length ? persisting.join(", ") : "none"} | resolved: ${resolved.length ? resolved.join(", ") : "none"}`
  );
  lines.push("");
  lines.push("### Next-window priorities");
  lines.push("```yaml");
  lines.push("priorities:");
  for (const p of priorities) {
    lines.push(`  - id: ${p.id}`);
    lines.push(`    action: ${p.action}`);
    if (p.scenes && p.scenes.length) lines.push(`    scenes: [${p.scenes.join(", ")}]`);
    if (p.add_test) lines.push(`    add_test: ${p.add_test}`);
  }
  lines.push("```");
  const section = lines.join("\n");

  if (write) {
    const body = digestText.startsWith(HEADER) ? digestText.slice(HEADER.length) : digestText;
    const next = `${HEADER}\n${section}\n${body ? `\n${body.trimStart()}` : ""}`;
    await mkdir(dirname(digestFile) === "" ? "." : dirname(digestFile), { recursive: true });
    await writeFile(digestFile, next, "utf8");
    await mkdir(dirname(watermarkFile), { recursive: true });
    await writeFile(watermarkFile, windowEnd, "utf8");
  }

  return { windowStart, windowEnd, records: records.length, section, clusters };
}

async function main() {
  const argv = process.argv.slice(2);
  const opt = (name: string): string | undefined => {
    const i = argv.indexOf(name);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const result = await consolidate({
    all: argv.includes("--all"),
    sessionsFile: opt("--sessions"),
    digestFile: opt("--digest"),
    watermarkFile: opt("--watermark")
  });
  if (result.records === 0) {
    console.log("No new sessions to consolidate.");
    return;
  }
  console.log(
    `Consolidated ${result.records} sessions (${result.windowStart} -> ${result.windowEnd}); ` +
      `${result.clusters.length} issue clusters. Digest updated.`
  );
}

if (fileURLToPath(import.meta.url) === resolve(process.argv[1] ?? "")) {
  main().catch((error) => {
    console.error("consolidate-feedback error:", error);
    process.exitCode = 1;
  });
}
